version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --log-level debug --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.common
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
      - /data/certs:/etc/nginx/certs
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    env_file:
      - ./.env.common
      - ./.env.prod
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - certbot
    command: /bin/sh -c "envsubst '$${MAIN_SERVER},$${NGINX_URL}' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/nginx.conf && cat /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
  certbot:
    image: tobi312/rpi-certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    env_file:
      - ./.env.common
      - ./.env.prod
    command: "/bin/sh -c 'certbot certonly --nginx -d $${MAIN_SERVER} -d www.$${MAIN_SERVER} --email $${MAIN_EMAIL} --text --agree-tos --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01; echo \"done\" '"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot --standalone renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  static_volume:
  media_volume:
